"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { User } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase-browser";

type Todo = { id: string; text: string; done: boolean; createdAt: number };
type Tab = "tasks" | "account" | "settings" | "changelog";
const cacheKey = (owner: string) => `fokus:todos:v3:${owner}`;
const readCache = (owner: string): Todo[] => { try { return JSON.parse(localStorage.getItem(cacheKey(owner)) || "[]"); } catch { return []; } };
const writeCache = (owner: string, items: Todo[]) => localStorage.setItem(cacheKey(owner), JSON.stringify(items));

const Icon = ({ name }: { name: "check" | "plus" | "tasks" | "user" | "gear" | "spark" | "logout" | "trash" | "arrow" }) => {
  const paths = { check: "M5 12.5l4 4L19 7", plus: "M12 5v14M5 12h14", tasks: "M9 6h11M9 12h11M9 18h11M4 6h.01M4 12h.01M4 18h.01", user: "M20 21a8 8 0 00-16 0M12 13a4 4 0 100-8 4 4 0 000 8", gear: "M12 15.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zM19.4 15a1.7 1.7 0 00.34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 00-1.88-.34 1.7 1.7 0 00-1 1.56V21h-3v-.08a1.7 1.7 0 00-1-1.56 1.7 1.7 0 00-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 006.08 15 1.7 1.7 0 004.52 14H4v-3h.52a1.7 1.7 0 001.56-1 1.7 1.7 0 00-.34-1.88l-.06-.06 2.12-2.12.06.06a1.7 1.7 0 001.88.34 1.7 1.7 0 001-1.56V4h3v.78a1.7 1.7 0 001 1.56 1.7 1.7 0 001.88-.34l.06-.06 2.12 2.12-.06.06A1.7 1.7 0 0017.92 10a1.7 1.7 0 001.56 1H20v3h-.52a1.7 1.7 0 00-1.56 1z", spark: "M12 3l1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3z", logout: "M10 17l5-5-5-5M15 12H3M15 4h4a2 2 0 012 2v12a2 2 0 01-2 2h-4", trash: "M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13", arrow: "M19 12H5M11 18l-6-6 6-6" };
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]} /></svg>;
};

export default function Home() {
  const [user, setUser] = useState<User | null>(null), [guest, setGuest] = useState(false), [ready, setReady] = useState(false);
  const [todos, setTodos] = useState<Todo[]>([]), [draft, setDraft] = useState(""), [tab, setTab] = useState<Tab>("tasks"), [notice, setNotice] = useState("");
  const [name, setName] = useState(""), [avatar, setAvatar] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState("");
  const loaded = useRef<string | null>(null);
  useEffect(() => { const mode = localStorage.getItem("todoAppMode"); if (mode === "guest") { setGuest(true); setTodos(readCache("guest")); } supabase.auth.getSession().then(({ data }) => { const current = data.session?.user || null; setUser(current); if (current) load(current); setReady(true); }); const { data } = supabase.auth.onAuthStateChange((_e, session) => { const current = session?.user || null; setUser(current); if (current) load(current); }); return () => data.subscription.unsubscribe(); }, []);
  async function load(current: User) { if (loaded.current === current.id) return; loaded.current = current.id; setTodos(readCache(current.id)); const [{ data: profile }, result] = await Promise.all([supabase.from("profiles").select("display_name,avatar_url").eq("id", current.id).maybeSingle(), supabase.from("todos").select("id,text,done,created_at").eq("user_id", current.id).order("created_at", { ascending: false })]); setName(profile?.display_name || current.user_metadata?.full_name || ""); setAvatar(profile?.avatar_url || ""); if (!result.error) { const next = (result.data || []).map(row => ({ id: row.id, text: row.text, done: row.done, createdAt: Date.parse(row.created_at) })); setTodos(next); writeCache(current.id, next); } }
  async function add() { const text = draft.trim(); if (!text) return; const item = { id: crypto.randomUUID(), text, done: false, createdAt: Date.now() }; const next = [item, ...todos]; setTodos(next); setDraft(""); writeCache(user?.id || "guest", next); if (user) await supabase.from("todos").insert({ id: item.id, user_id: user.id, text, done: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }); }
  async function toggle(todo: Todo) { const next = todos.map(t => t.id === todo.id ? { ...t, done: !t.done } : t); setTodos(next); writeCache(user?.id || "guest", next); if (user) await supabase.from("todos").update({ done: !todo.done, updated_at: new Date().toISOString() }).eq("id", todo.id); }
  async function remove(todo: Todo) { const next = todos.filter(t => t.id !== todo.id); setTodos(next); writeCache(user?.id || "guest", next); if (user) await supabase.from("todos").delete().eq("id", todo.id); }
  async function logout() { await supabase.auth.signOut(); setUser(null); setGuest(false); setTodos([]); localStorage.removeItem("todoAppMode"); }
  if (!ready) return <div className="loading"><span className="logo"><Icon name="check" /></span><p>Dein Fokus wird vorbereitet …</p></div>;
  if (!user && !guest) return <Auth onDone={() => setReady(true)} onGuest={() => { setGuest(true); localStorage.setItem("todoAppMode", "guest"); setTodos(readCache("guest")); }} />;
  const open = todos.filter(t => !t.done).length, done = todos.length - open, progress = todos.length ? Math.round(done / todos.length * 100) : 0;
  const firstName = name.trim().split(" ")[0] || (guest ? "du" : "du");
  return <main className="shell">
    <aside className="sidebar"><div className="wordmark"><span className="logo"><Icon name="check" /></span><b>Fokus</b></div><nav>{[["tasks","tasks","Heute"],["account","user","Profil"],["settings","gear","Einstellungen"],["changelog","spark","Neuigkeiten"]].map(([key, icon, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key as Tab)}><Icon name={icon as any}/><span>{label}</span></button>)}</nav><div className="sidebar-quote"><Icon name="spark"/><p>Kleine Schritte.<br/><b>Spürbarer Fortschritt.</b></p></div><button className="logout" onClick={logout}><Icon name="logout"/><span>Abmelden</span></button></aside>
    <section className="workspace">
      <header className="mobile-head"><div className="wordmark"><span className="logo"><Icon name="check"/></span><b>Fokus</b></div><span className="avatar">{name?.[0]?.toUpperCase() || "F"}</span></header>
      {tab === "tasks" && <><header className="welcome"><div><p className="kicker">SAMSTAG · DEIN TAG</p><h1>Guten Tag, {firstName}.</h1><p>Was wäre heute ein kleiner, aber bedeutender Erfolg?</p></div><div className="progress" style={{"--progress": `${progress * 3.6}deg`} as React.CSSProperties}><span><b>{progress}%</b><small>geschafft</small></span></div></header>
        <section className="focus-card"><div className="orb one"/><div className="orb two"/><div><span className="focus-label"><Icon name="spark"/> HEUTIGER FOKUS</span><h2>{open ? `Noch ${open} ${open === 1 ? "Sache" : "Dinge"}. Du schaffst das.` : "Alles geschafft. Genieß den Moment."}</h2><p>{open ? "Beginne mit der Aufgabe, die dir danach am meisten Ruhe gibt." : "Fortschritt darf sich auch leicht anfühlen."}</p></div><div className="focus-score"><b>{done}</b><span>von {todos.length || 0}<br/>erledigt</span></div></section>
        <section className="task-area"><div className="section-title"><div><h2>Meine Aufgaben</h2><p>{open ? `${open} offen · ${done} erledigt` : "Deine Liste ist wunderbar leer"}</p></div></div><div className="composer"><span><Icon name="plus"/></span><input aria-label="Neue Aufgabe" value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} placeholder="Was möchtest du aus dem Kopf bekommen?"/><button onClick={add} disabled={!draft.trim()}>Hinzufügen</button></div><div className="task-list">{todos.map(todo => <article className={`task ${todo.done ? "done" : ""}`} key={todo.id}><button className="check" aria-label={todo.done ? "Als offen markieren" : "Als erledigt markieren"} onClick={() => toggle(todo)}>{todo.done && <Icon name="check"/>}</button><div><span>{todo.text}</span><small>{todo.done ? "Geschafft – gut gemacht" : "Heute"}</small></div><button className="delete" aria-label="Aufgabe löschen" onClick={() => remove(todo)}><Icon name="trash"/></button></article>)}{!todos.length && <div className="empty"><span><Icon name="spark"/></span><h3>Hier ist Platz für Wichtiges.</h3><p>Schreib deine erste Aufgabe auf – dein Kopf muss sie nicht länger festhalten.</p></div>}</div></section></>}
      {tab === "account" && <Panel title="Dein Profil" subtitle="Ein ruhiger Ort für deine persönlichen Daten." back={() => setTab("tasks")}><div className="profile"><div className="avatar large">{avatar ? <img src={avatar} alt="Profilbild"/> : name?.[0]?.toUpperCase() || "F"}</div><div><b>{name || "Dein Name"}</b><span>{user?.email || "Gastmodus"}</span></div></div><Field label="Anzeigename" value={name} set={setName}/><Field label="Profilbild-URL" value={avatar} set={setAvatar}/><button className="primary" onClick={async()=>{ if(!user)return; const {error}=await supabase.from("profiles").upsert({id:user.id,display_name:name,avatar_url:avatar,email:user.email}); setNotice(error?.message||"Dein Profil wurde gespeichert.");}}>Änderungen speichern</button><p className="notice">{notice}</p></Panel>}
      {tab === "settings" && <Panel title="Einstellungen" subtitle="So fühlt sich Fokus für dich richtig an." back={() => setTab("tasks")}><div className="setting"><div><b>Lokale Aufgabendaten</b><span>Löscht nur den Zwischenspeicher auf diesem Gerät.</span></div><button onClick={()=>{Object.keys(localStorage).filter(k=>k.startsWith("fokus:todos")).forEach(k=>localStorage.removeItem(k));setTodos([])}}>Leeren</button></div><div className="setting"><div><b>Reduzierte Ablenkung</b><span>Fokus verwendet bewusst keine Benachrichtigungen.</span></div><span className="toggle on"/></div></Panel>}
      {tab === "changelog" && <Panel title="Was es Neues gibt" subtitle="Fokus wächst ruhig und mit Bedacht." back={() => setTab("tasks")}><div className="release"><span>AKTUELL · V2.1</span><h3>Ein persönlicherer Fokus</h3><p>Neues Profil, bessere mobile Navigation und ein klarerer Tagesfortschritt.</p></div><div className="release muted"><span>ALS NÄCHSTES</span><h3>Mehrere Listen & Termine</h3><p>Organisiere Projekte getrennt und gib Aufgaben einen passenden Zeitpunkt.</p></div></Panel>}
    </section>
    <nav className="mobile-nav">{[["tasks","tasks","Heute"],["account","user","Profil"],["settings","gear","Optionen"]].map(([key,icon,label])=><button className={tab===key?"active":""} onClick={()=>setTab(key as Tab)} key={key}><Icon name={icon as any}/><span>{label}</span></button>)}</nav>
  </main>;
}

function Panel({title,subtitle,back,children}:{title:string;subtitle:string;back:()=>void;children:React.ReactNode}) { return <section className="panel"><button className="back" onClick={back}><Icon name="arrow"/> Zurück zu Heute</button><header><p className="kicker">DEIN FOKUS</p><h1>{title}</h1><p>{subtitle}</p></header><div className="panel-body">{children}</div></section> }
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)}/></label> }
function Auth({onDone,onGuest}:{onDone:()=>void;onGuest:()=>void}) { const [register,setRegister]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();const result=register?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});if(result.error)setError(result.error.message);else onDone()} return <main className="auth"><section className="auth-story"><div className="wordmark"><span className="logo"><Icon name="check"/></span><b>Fokus</b></div><div><p className="kicker">RUHE FÜR DEINEN KOPF</p><h1>Weniger festhalten.<br/><em>Mehr vorankommen.</em></h1><p>Deine Aufgaben an einem klaren Ort – damit du dich wieder auf das konzentrieren kannst, was gerade zählt.</p><div className="promise"><span><Icon name="check"/></span><div><b>Einfach anfangen</b><small>Keine komplizierten Systeme. Nur dein nächster Schritt.</small></div></div><div className="promise"><span><Icon name="check"/></span><div><b>Überall bei dir</b><small>Synchronisiert und sicher auf allen Geräten.</small></div></div></div><blockquote>„Du musst nicht alles schaffen. Nur das Richtige als Nächstes.“</blockquote></section><form onSubmit={submit}><span className="auth-pill">DEIN RUHIGER WORKSPACE</span><h2>{register?"Dein Fokus beginnt hier.":"Schön, dass du wieder da bist."}</h2><p>{register?"Erstelle dein kostenloses Konto.":"Melde dich an und mach dort weiter, wo du aufgehört hast."}</p>{register&&<Field label="Dein Name" value={name} set={setName}/>}<Field label="E-Mail-Adresse" value={email} set={setEmail} type="email"/><Field label="Passwort" value={password} set={setPassword} type="password"/><button className="auth-submit">{register?"Kostenlos starten":"In meinen Fokus"} <Icon name="arrow"/></button><button type="button" className="guest" onClick={onGuest}>Erst einmal ohne Konto ausprobieren</button>{error&&<p className="error">{error}</p>}<p className="switch">{register?"Schon dabei?":"Noch kein Konto?"} <button type="button" onClick={()=>setRegister(!register)}>{register?"Anmelden":"Jetzt starten"}</button></p></form></main> }
